version: 1

formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(filename)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file_handler:
    class: logging.FileHandler
    filename: ../../hw1_tmp/logs/prediction.log
    level: DEBUG
    formatter: simple

root:
  level: DEBUG
  handlers: [ file_handler ]
