dataset_path: "../hw1_tmp/data_without_target.csv"
model_path: "../hw1_tmp/model.pkl"
transformer_path: "../hw1_tmp/transformer.pkl"
predictions_path: "../hw1_tmp/predicts.csv"
feature_params:
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
    - "sex"
    - "fbs"
    - "exang"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
