input_data_path: "../hw1_tmp/heart.csv"
model_path: "../hw1_tmp/model.pkl"
transformer_path: "../hw1_tmp/transformer.pkl"
metrics_path: "../hw1_tmp/metrics.json"
splitting_params:
  val_size: 0.3
  random_state: 3
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
    - "sex"
    - "fbs"
    - "exang"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
