splitting_params:
  val_size: 0.1
  random_state: 3
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
    - "sex"
    - "fbs"
    - "exang"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
