apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: nordream/inference_service:v1
      name: online-inference
      ports:
        - containerPort: 8000
